# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a83f98af2c9af5bfabb59e2c51ea05a9d5c56319263b72749627729d8afdf2193e2875ac665cb8e4cf6b3fc9e5c9219e6d540efecf9e2e5d4b1aa4ec22479d4

test:
  secret_key_base: 3cae3c9128bfb507b92fa7dc66a4b1da97830c42a4e9b5101edccd25a0a88740506b2deef3d9b612b7b4f735f917e6c9557d0bdc6f3abcb696500467cf521190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
